### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by actionschnitzel** [jjk4/pmar#3]
python3.10-venv(Ubuntu22.04) (python3-venv) is required to create a Virtual Environment.
please add to README

**Comment by jjk4** [comment]
Is a specific version required, or do we just need python3-venv?

**Comment by actionschnitzel** [comment]
When installing python3-venv on Ubuntu it defaults to version 3.10. Whats is your version? I think it does not matter.
Just had to install it cause venv is not installed by default.

**Comment by jjk4** [comment]
done in https://github.com/jjk4/pmar/commit/8cd323c27e849c2baf479f0fbc90bf3e3c9d8582
